In [1]:
!pip install psycopg2-binary --break-system-packages

WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)
Requirement already satisfied: psycopg2-binary in /Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages (2.9.11)
WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)
WARNING: Ignoring invalid distribution ~cipy (/Users/samberkhout/miniconda3/envs/jupyter/lib/python3.11/site-packages)

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://samberkhout@localhost:5434/rister_prod17")

In [ ]:
df = pd.read_sql(
    """
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_type = 'BASE TABLE'
    AND table_schema NOT IN ('pg_catalog', 'information_schema')
    ORDER BY table_schema, table_name
""",
    engine,
)

print(df.to_string())

In [5]:
def get_table(schema, table, columns=None):
    cols = ", ".join(f'"{c}"' for c in columns) if columns else "*"
    df = pd.read_sql(f'SELECT {cols} FROM "{schema}"."{table}"', engine)
    df = df.rename(columns={"Id": f"{table.lower()}_id"})
    df = df.rename(columns={"Name": f"{table.lower()}name"})
    return df

# orders

In [6]:
orders = get_table("Orders", "Orders")

In [7]:
orders.head()

,orders_id,TenantId,ClientId,ContactId,OrderStatus,Instructions,ProjectId,ContactSupplierId,ProjectSupplierId,SupplierId,Type,AppointmentId,CompanyId,CodePostfix,CodePrefix,CreatedByUserId,Reference
0,1a141e27-de90-4814-b68d-f096680e539f,8b0e12de-9d8c-43ad-8936-2e79faa3f741,53860227-8c37-4408-a494-fa3e4aee88e9,None,9,None,None,None,None,None,1.0,None,2e7682b0-1826-4bd4-95b5-9e7b19fd3e90,864,2025,80faee07-d186-4fac-b3a6-f507221c9c0e,None
1,16cc0261-0cec-47c4-ac52-9ceb24998900,8b0e12de-9d8c-43ad-8936-2e79faa3f741,67044d6c-f80d-4ff6-ba13-80f75681e383,None,9,None,None,None,None,None,1.0,None,2e7682b0-1826-4bd4-95b5-9e7b19fd3e90,591,2025,a15f21b5-7775-44ea-b2d3-fc1efeefb647,None
2,32bc1f91-5edb-4769-8629-79f7079cfb4e,8b0e12de-9d8c-43ad-8936-2e79faa3f741,67044d6c-f80d-4ff6-ba13-80f75681e383,None,9,None,None,None,None,None,1.0,None,2e7682b0-1826-4bd4-95b5-9e7b19fd3e90,724,2025,80faee07-d186-4fac-b3a6-f507221c9c0e,None
3,162b1d0b-2beb-455a-9176-31dc61208aac,8b0e12de-9d8c-43ad-8936-2e79faa3f741,389ada73-2c80-4765-af68-264616f259d2,None,9,None,None,None,None,None,1.0,None,2e7682b0-1826-4bd4-95b5-9e7b19fd3e90,904,2025,7b2787d4-ca0e-450b-87d7-01a557b47af1,None
4,a655a5ec-effc-42a5-bbaf-e5274e8c6ce9,f5ab1b29-de37-4818-bb05-b2fe57ce6768,6741cb38-6061-4937-ae8c-e14437f7a74f,None,9,None,None,None,None,None,1.0,None,2a46854b-c33e-429b-a0cb-16ee7d9d615a,2996,2025,647ee238-5b96-4824-9154-2d63a4446671,None

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34923 entries, 0 to 34922
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   orders_id          34923 non-null  object
 1   TenantId           34923 non-null  object
 2   ClientId           34923 non-null  object
 3   ContactId          1268 non-null   object
 4   OrderStatus        34923 non-null  int64
 5   Instructions       2658 non-null   object
 6   ProjectId          3148 non-null   object
 7   ContactSupplierId  0 non-null      object
 8   ProjectSupplierId  1 non-null      object
 9   SupplierId         251 non-null    object
 10  Type               34922 non-null  float64
 11  AppointmentId      0 non-null      object
 12  CompanyId          34923 non-null  object
 13  CodePostfix        34923 non-null  int64
 14  CodePrefix         34923 non-null  int64
 15  CreatedByUserId    34923 non-null  object
 16  Reference          724 non-null    object
dtypes: float64(1), int64(3), object(13)
memory usage: 4.5+ MB

# order_service_line

In [9]:
order_service_line = get_table("Orders", "OrderServiceLine")

In [10]:
order_service_line.head()

,orderserviceline_id,OrderServiceId,EmployeeId,ServiceLineId,orderservicelinename,IsAttachment
0,46063b18-b46f-42fe-91ba-f1edb5875ac2,d395a0b0-df98-4a98-9a90-2111c573d171,f140f35a-3bce-429a-83c7-62a740a01f9a,bce95084-2607-4ee2-977f-4e778e0852f4,Kuhn ronde balen pers incl. wik. 6 lagen,False
1,1c062078-cf15-4b39-b958-372f5065f6d1,c8fcc1b7-25f6-4d34-8e22-3ba7cdeaa378,00000000-0000-0000-0000-000000000000,1a3c0309-4c64-4c65-b71b-91bf7b1412c5,Kraan,False
2,56928478-db32-4d47-aa5e-ff93ec216de2,96056b77-15d5-4d52-b8dc-fee6a5c3fe61,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,ddfc6777-8d48-426d-be11-70b464421688,Mobiele Kraan,False
3,83ce6728-df33-4478-98e1-88f5203cb6e1,c6021691-8aff-4a4e-af17-85381e7bde9a,8ce44d18-4b2a-4564-ae75-39ab03024406,66572589-bcc2-4bc0-8352-bac80524977c,Pomp,False
4,a0372f4f-bc84-4e76-99c5-350685b91a8c,60d49099-c502-47c8-a7a1-43caf71fbe31,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,e2253dd7-b70c-4946-bf22-0d1e4523904e,Gras zaaien,None

# order_services

In [11]:
order_services = get_table("Orders", "OrderServices")

In [12]:
order_services.head()

,orderservices_id,OrderId,ServiceId,orderservicesname,DisplayPriority,ReferenceId
0,606d73e9-8c93-47fd-9a5e-ef38106f8a23,64cedaa5-3dfe-484a-b4a0-95664a7ff9c1,88c46849-8dce-46a6-a8b4-7af99c92dcba,Zodebemesten,0.0,76f6d794-640c-4c63-ad44-16335b33585a
1,4a673d59-0c47-4ff9-8acb-d2e7f1d78cfb,7607a38a-1e6a-4ba2-b885-928d0f59243e,445e03b3-6495-410d-b314-1a91a4290905,Shovel 15ton,NaN,00000000-0000-0000-0000-000000000000
2,8dd64e51-2a3c-4ffc-825a-955e26895e2e,7607a38a-1e6a-4ba2-b885-928d0f59243e,445e03b3-6495-410d-b314-1a91a4290905,Shovel 15ton,NaN,00000000-0000-0000-0000-000000000000
3,ae5da46b-5e8e-4352-86ba-3ad6cfe7ab7f,6c704e6f-9a17-4af2-9b50-c548906c254e,c80505de-990b-4ee8-b6eb-e5220a3d6a5b,Spuiten uien Ecorobotix,1.0,d6c564ba-abc8-6137-76c8-8787792ec8c6
4,b1e5ec43-e14b-4031-ae8e-e41f7b2216c7,cd0dbec8-e867-4382-a5b7-74c54fefa7cd,3b9e8cef-c4c2-4fed-8226-d714ca43bea4,Kipper 15 m3,0.0,02ae2263-8986-409e-9bb0-8824a2a29228

In [13]:
order_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38015 entries, 0 to 38014
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   orderservices_id   38015 non-null  object
 1   OrderId            38015 non-null  object
 2   ServiceId          38015 non-null  object
 3   orderservicesname  38015 non-null  object
 4   DisplayPriority    38013 non-null  float64
 5   ReferenceId        38015 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.7+ MB

In [14]:
order_services = order_services.merge(
    order_service_line, left_on="orderservices_id", right_on="OrderServiceId", how="right"
)

In [15]:
order_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39871 entries, 0 to 39870
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      39871 non-null  object
 1   OrderId               39871 non-null  object
 2   ServiceId             39871 non-null  object
 3   orderservicesname     39871 non-null  object
 4   DisplayPriority       39871 non-null  float64
 5   ReferenceId           39871 non-null  object
 6   orderserviceline_id   39871 non-null  object
 7   OrderServiceId        39871 non-null  object
 8   EmployeeId            39871 non-null  object
 9   ServiceLineId         39871 non-null  object
 10  orderservicelinename  39871 non-null  object
 11  IsAttachment          39004 non-null  object
dtypes: float64(1), object(11)
memory usage: 3.7+ MB

In [16]:
df = order_services.merge(orders, left_on=["OrderId"], right_on=["orders_id"], how="left")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39871 entries, 0 to 39870
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      39871 non-null  object
 1   OrderId               39871 non-null  object
 2   ServiceId             39871 non-null  object
 3   orderservicesname     39871 non-null  object
 4   DisplayPriority       39871 non-null  float64
 5   ReferenceId           39871 non-null  object
 6   orderserviceline_id   39871 non-null  object
 7   OrderServiceId        39871 non-null  object
 8   EmployeeId            39871 non-null  object
 9   ServiceLineId         39871 non-null  object
 10  orderservicelinename  39871 non-null  object
 11  IsAttachment          39004 non-null  object
 12  orders_id             39871 non-null  object
 13  TenantId              39871 non-null  object
 14  ClientId              39871 non-null  object
 15  ContactId             2147 non-null   object
 16  OrderStatus           39871 non-null  int64
 17  Instructions          4047 non-null   object
 18  ProjectId             4600 non-null   object
 19  ContactSupplierId     0 non-null      object
 20  ProjectSupplierId     2 non-null      object
 21  SupplierId            302 non-null    object
 22  Type                  39871 non-null  float64
 23  AppointmentId         0 non-null      object
 24  CompanyId             39871 non-null  object
 25  CodePostfix           39871 non-null  int64
 26  CodePrefix            39871 non-null  int64
 27  CreatedByUserId       39871 non-null  object
 28  Reference             1110 non-null   object
dtypes: float64(2), int64(3), object(24)
memory usage: 8.8+ MB

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39871 entries, 0 to 39870
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      39871 non-null  object
 1   OrderId               39871 non-null  object
 2   ServiceId             39871 non-null  object
 3   orderservicesname     39871 non-null  object
 4   DisplayPriority       39871 non-null  float64
 5   ReferenceId           39871 non-null  object
 6   orderserviceline_id   39871 non-null  object
 7   OrderServiceId        39871 non-null  object
 8   EmployeeId            39871 non-null  object
 9   ServiceLineId         39871 non-null  object
 10  orderservicelinename  39871 non-null  object
 11  IsAttachment          39004 non-null  object
 12  orders_id             39871 non-null  object
 13  TenantId              39871 non-null  object
 14  ClientId              39871 non-null  object
 15  ContactId             2147 non-null   object
 16  OrderStatus           39871 non-null  int64
 17  Instructions          4047 non-null   object
 18  ProjectId             4600 non-null   object
 19  ContactSupplierId     0 non-null      object
 20  ProjectSupplierId     2 non-null      object
 21  SupplierId            302 non-null    object
 22  Type                  39871 non-null  float64
 23  AppointmentId         0 non-null      object
 24  CompanyId             39871 non-null  object
 25  CodePostfix           39871 non-null  int64
 26  CodePrefix            39871 non-null  int64
 27  CreatedByUserId       39871 non-null  object
 28  Reference             1110 non-null   object
dtypes: float64(2), int64(3), object(24)
memory usage: 8.8+ MB

# service_line_units

In [19]:
service_line_units = get_table("Orders", "ServiceLineUnits")

In [20]:
Units = get_table("Shared", "Units")

In [21]:
service_line_units = service_line_units.merge(Units, left_on="UnitId", right_on="units_id")

In [22]:
service_line_units.head()

,ServiceLineId,UnitId,Amount,units_id,unitsname,Code,IsoCode,EdiCode,IsArchived,IsTime,IsAlwaysSelectable
0,0ccdd9f3-cb32-41cb-a1ea-ce15038cd631,7,0.0,7,Hectare,HA,HAR,HA,False,False,False
1,0ccdd9f3-cb32-41cb-a1ea-ce15038cd631,23,0.0,23,Uur,UUR,HUR,UUR,False,True,False
2,2062a767-fdd3-4d0b-bc24-7232d67c02ec,7,0.0,7,Hectare,HA,HAR,HA,False,False,False
3,2062a767-fdd3-4d0b-bc24-7232d67c02ec,23,0.0,23,Uur,UUR,HUR,UUR,False,True,False
4,5b90f74c-bf78-4ce0-b73c-8183b8c218e9,23,0.0,23,Uur,UUR,HUR,UUR,False,True,False

In [23]:
service_line_units.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46427 entries, 0 to 46426
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ServiceLineId       46427 non-null  object
 1   UnitId              46427 non-null  int64
 2   Amount              46427 non-null  float64
 3   units_id            46427 non-null  int64
 4   unitsname           46427 non-null  object
 5   Code                46427 non-null  object
 6   IsoCode             46427 non-null  object
 7   EdiCode             46427 non-null  object
 8   IsArchived          46427 non-null  bool
 9   IsTime              46427 non-null  bool
 10  IsAlwaysSelectable  46427 non-null  bool
dtypes: bool(3), float64(1), int64(2), object(5)
memory usage: 3.0+ MB

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39871 entries, 0 to 39870
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      39871 non-null  object
 1   OrderId               39871 non-null  object
 2   ServiceId             39871 non-null  object
 3   orderservicesname     39871 non-null  object
 4   DisplayPriority       39871 non-null  float64
 5   ReferenceId           39871 non-null  object
 6   orderserviceline_id   39871 non-null  object
 7   OrderServiceId        39871 non-null  object
 8   EmployeeId            39871 non-null  object
 9   ServiceLineId         39871 non-null  object
 10  orderservicelinename  39871 non-null  object
 11  IsAttachment          39004 non-null  object
 12  orders_id             39871 non-null  object
 13  TenantId              39871 non-null  object
 14  ClientId              39871 non-null  object
 15  ContactId             2147 non-null   object
 16  OrderStatus           39871 non-null  int64
 17  Instructions          4047 non-null   object
 18  ProjectId             4600 non-null   object
 19  ContactSupplierId     0 non-null      object
 20  ProjectSupplierId     2 non-null      object
 21  SupplierId            302 non-null    object
 22  Type                  39871 non-null  float64
 23  AppointmentId         0 non-null      object
 24  CompanyId             39871 non-null  object
 25  CodePostfix           39871 non-null  int64
 26  CodePrefix            39871 non-null  int64
 27  CreatedByUserId       39871 non-null  object
 28  Reference             1110 non-null   object
dtypes: float64(2), int64(3), object(24)
memory usage: 8.8+ MB

In [25]:
df = df.merge(
    service_line_units, left_on="orderserviceline_id", right_on="ServiceLineId", how="left"
)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46810 entries, 0 to 46809
Data columns (total 40 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      46810 non-null  object
 1   OrderId               46810 non-null  object
 2   ServiceId             46810 non-null  object
 3   orderservicesname     46810 non-null  object
 4   DisplayPriority       46810 non-null  float64
 5   ReferenceId           46810 non-null  object
 6   orderserviceline_id   46810 non-null  object
 7   OrderServiceId        46810 non-null  object
 8   EmployeeId            46810 non-null  object
 9   ServiceLineId_x       46810 non-null  object
 10  orderservicelinename  46810 non-null  object
 11  IsAttachment          45906 non-null  object
 12  orders_id             46810 non-null  object
 13  TenantId              46810 non-null  object
 14  ClientId              46810 non-null  object
 15  ContactId             2148 non-null   object
 16  OrderStatus           46810 non-null  int64
 17  Instructions          4599 non-null   object
 18  ProjectId             4652 non-null   object
 19  ContactSupplierId     0 non-null      object
 20  ProjectSupplierId     5 non-null      object
 21  SupplierId            614 non-null    object
 22  Type                  46810 non-null  float64
 23  AppointmentId         0 non-null      object
 24  CompanyId             46810 non-null  object
 25  CodePostfix           46810 non-null  int64
 26  CodePrefix            46810 non-null  int64
 27  CreatedByUserId       46810 non-null  object
 28  Reference             1571 non-null   object
 29  ServiceLineId_y       46427 non-null  object
 30  UnitId                46427 non-null  float64
 31  Amount                46427 non-null  float64
 32  units_id              46427 non-null  float64
 33  unitsname             46427 non-null  object
 34  Code                  46427 non-null  object
 35  IsoCode               46427 non-null  object
 36  EdiCode               46427 non-null  object
 37  IsArchived            46427 non-null  object
 38  IsTime                46427 non-null  object
 39  IsAlwaysSelectable    46427 non-null  object
dtypes: float64(5), int64(3), object(32)
memory usage: 14.3+ MB

# "Orders"."ServiceLineEquipment"

In [27]:
ServiceLineEquipment = get_table("Orders", "ServiceLineEquipment")

In [28]:
ServiceLineEquipment.head()

,ServiceLineId,EquipmentId,EquipmentType
0,774db101-8821-416f-a77a-246b772df40f,459cd2bc-c68f-456f-bbd6-6b32a8561e64,0
1,774db101-8821-416f-a77a-246b772df40f,5cc34396-450d-49da-b1f1-48771417ac58,1
2,8b599cc6-24dc-4468-968b-7c03746850f1,459cd2bc-c68f-456f-bbd6-6b32a8561e64,0
3,d644db9a-036b-417c-a2b4-73a064c4b4db,c87450c9-5179-47d7-bc50-d6256c1270d2,0
4,c7c5d90a-a785-4646-9799-3feb56351363,73bf5cf0-bd88-466d-9b44-2d91800691dd,0

In [29]:
ServiceLineEquipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15023 entries, 0 to 15022
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ServiceLineId  15023 non-null  object
 1   EquipmentId    15023 non-null  object
 2   EquipmentType  15023 non-null  int64
dtypes: int64(1), object(2)
memory usage: 352.2+ KB

In [30]:
df = df.merge(
    ServiceLineEquipment, left_on="orderserviceline_id", right_on="ServiceLineId", how="left"
)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 43 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderservices_id      50373 non-null  object
 1   OrderId               50373 non-null  object
 2   ServiceId             50373 non-null  object
 3   orderservicesname     50373 non-null  object
 4   DisplayPriority       50373 non-null  float64
 5   ReferenceId           50373 non-null  object
 6   orderserviceline_id   50373 non-null  object
 7   OrderServiceId        50373 non-null  object
 8   EmployeeId            50373 non-null  object
 9   ServiceLineId_x       50373 non-null  object
 10  orderservicelinename  50373 non-null  object
 11  IsAttachment          49463 non-null  object
 12  orders_id             50373 non-null  object
 13  TenantId              50373 non-null  object
 14  ClientId              50373 non-null  object
 15  ContactId             2171 non-null   object
 16  OrderStatus           50373 non-null  int64
 17  Instructions          4855 non-null   object
 18  ProjectId             4850 non-null   object
 19  ContactSupplierId     0 non-null      object
 20  ProjectSupplierId     11 non-null     object
 21  SupplierId            642 non-null    object
 22  Type                  50373 non-null  float64
 23  AppointmentId         0 non-null      object
 24  CompanyId             50373 non-null  object
 25  CodePostfix           50373 non-null  int64
 26  CodePrefix            50373 non-null  int64
 27  CreatedByUserId       50373 non-null  object
 28  Reference             1579 non-null   object
 29  ServiceLineId_y       49932 non-null  object
 30  UnitId                49932 non-null  float64
 31  Amount                49932 non-null  float64
 32  units_id              49932 non-null  float64
 33  unitsname             49932 non-null  object
 34  Code                  49932 non-null  object
 35  IsoCode               49932 non-null  object
 36  EdiCode               49932 non-null  object
 37  IsArchived            49932 non-null  object
 38  IsTime                49932 non-null  object
 39  IsAlwaysSelectable    49932 non-null  object
 40  ServiceLineId         17924 non-null  object
 41  EquipmentId           17924 non-null  object
 42  EquipmentType         17924 non-null  float64
dtypes: float64(6), int64(3), object(34)
memory usage: 16.5+ MB

# relations

In [32]:
relation = get_table("Management", "Relations")

In [33]:
relation.head()

,relations_id,relationsname,TenantId,Code,Attention,ChamberOfCommerce,Email,Infix,Initials,MobilePhoneNumber,...,BrsNumber,ChamberOfCommerceBranchNumber,IsCreditor,IsDebtor,OinNumber,UbnNumber,VatNumber,ActiveExpansions,IsDeleted,IsDemo
0,5253d0f4-6bbe-4381-8d61-2b6c093a2c4c,Melkveehouderij de Oostermaat,73d1596b-3ea2-4798-b499-25cb3c0f3898,13715,Rindert van de Brake,None,deoostermaat@outlook.com,None,None,0646735589,...,NaN,None,False,True,None,NaN,None,NaN,False,False
1,0329c509-408d-42cc-b091-1bd697d718e9,Westerink multiservice,73d1596b-3ea2-4798-b499-25cb3c0f3898,13718,None,73035629,westerinkmultiservice@outlook.com,None,None,0622237803,...,NaN,None,False,True,None,NaN,None,NaN,False,False
2,6068dd76-00dd-4077-8c06-8e3383aaef8e,J.P. Schilder B.V.,40468dd2-328f-4542-b69e-3882aecc8099,1216,None,None,facturen@jpschilder.nl,None,None,None,...,NaN,None,False,True,None,NaN,None,NaN,False,False
3,c31f9977-d517-47f3-9bf5-0e59bb0246eb,Het Lunterse Veld,ae529712-0964-4043-98b6-dda69a33d457,10478,None,None,factuur@hetlunterseveld.nl,None,None,None,...,NaN,None,False,True,None,NaN,None,NaN,False,False
4,2a1135c8-1160-4a77-8a80-27c503f8cb8e,van den Berg Landbouwbedrijf bv,9c822f1c-e7d1-4dd7-b814-148ffce6cace,800282,None,None,facturenvandenberglandbouw@outlook.com,17176565,None,06 45798438,...,NaN,None,False,True,,NaN,,NaN,False,False

In [34]:
relation = relation.drop(columns="TenantId")

In [35]:
relation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29765 entries, 0 to 29764
Data columns (total 27 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   relations_id                            29765 non-null  object
 1   relationsname                           29765 non-null  object
 2   Code                                    29765 non-null  object
 3   Attention                               1097 non-null   object
 4   ChamberOfCommerce                       4531 non-null   object
 5   Email                                   15287 non-null  object
 6   Infix                                   1265 non-null   object
 7   Initials                                2498 non-null   object
 8   MobilePhoneNumber                       5850 non-null   object
 9   PhoneNumber                             10499 non-null  object
 10  Prefixes                                1251 non-null   object
 11  Website                                 1984 non-null   object
 12  PostalAddressId                         29745 non-null  object
 13  VisitationAddressId                     28828 non-null  object
 14  BlockUserLogins                         29765 non-null  bool
 15  IsPostalAddressSameAsVisitationAddress  29765 non-null  bool
 16  ApprovalNumber                          0 non-null      object
 17  BrsNumber                               54 non-null     float64
 18  ChamberOfCommerceBranchNumber           58 non-null     object
 19  IsCreditor                              29765 non-null  bool
 20  IsDebtor                                29765 non-null  bool
 21  OinNumber                               5585 non-null   object
 22  UbnNumber                               1 non-null      float64
 23  VatNumber                               8575 non-null   object
 24  ActiveExpansions                        24 non-null     float64
 25  IsDeleted                               29765 non-null  bool
 26  IsDemo                                  29765 non-null  bool
dtypes: bool(6), float64(3), object(18)
memory usage: 4.9+ MB

In [36]:
df = df.merge(relation, left_on="TenantId", right_on="relations_id", how="left")

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 70 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   orderservices_id                        50373 non-null  object
 1   OrderId                                 50373 non-null  object
 2   ServiceId                               50373 non-null  object
 3   orderservicesname                       50373 non-null  object
 4   DisplayPriority                         50373 non-null  float64
 5   ReferenceId                             50373 non-null  object
 6   orderserviceline_id                     50373 non-null  object
 7   OrderServiceId                          50373 non-null  object
 8   EmployeeId                              50373 non-null  object
 9   ServiceLineId_x                         50373 non-null  object
 10  orderservicelinename                    50373 non-null  object
 11  IsAttachment                            49463 non-null  object
 12  orders_id                               50373 non-null  object
 13  TenantId                                50373 non-null  object
 14  ClientId                                50373 non-null  object
 15  ContactId                               2171 non-null   object
 16  OrderStatus                             50373 non-null  int64
 17  Instructions                            4855 non-null   object
 18  ProjectId                               4850 non-null   object
 19  ContactSupplierId                       0 non-null      object
 20  ProjectSupplierId                       11 non-null     object
 21  SupplierId                              642 non-null    object
 22  Type                                    50373 non-null  float64
 23  AppointmentId                           0 non-null      object
 24  CompanyId                               50373 non-null  object
 25  CodePostfix                             50373 non-null  int64
 26  CodePrefix                              50373 non-null  int64
 27  CreatedByUserId                         50373 non-null  object
 28  Reference                               1579 non-null   object
 29  ServiceLineId_y                         49932 non-null  object
 30  UnitId                                  49932 non-null  float64
 31  Amount                                  49932 non-null  float64
 32  units_id                                49932 non-null  float64
 33  unitsname                               49932 non-null  object
 34  Code_x                                  49932 non-null  object
 35  IsoCode                                 49932 non-null  object
 36  EdiCode                                 49932 non-null  object
 37  IsArchived                              49932 non-null  object
 38  IsTime                                  49932 non-null  object
 39  IsAlwaysSelectable                      49932 non-null  object
 40  ServiceLineId                           17924 non-null  object
 41  EquipmentId                             17924 non-null  object
 42  EquipmentType                           17924 non-null  float64
 43  relations_id                            50373 non-null  object
 44  relationsname                           50373 non-null  object
 45  Code_y                                  50373 non-null  object
 46  Attention                               0 non-null      object
 47  ChamberOfCommerce                       50373 non-null  object
 48  Email                                   31267 non-null  object
 49  Infix                                   0 non-null      object
 50  Initials                                0 non-null      object
 51  MobilePhoneNumber                       19870 non-null  object
 52  PhoneNumber                             7798 non-null   object
 53  Prefixes                                0 non-null      object
 54  Website                                 8595 non-null   object
 55  PostalAddressId                         50363 non-null  object
 56  VisitationAddressId                     50373 non-null  object
 57  BlockUserLogins                         50373 non-null  bool
 58  IsPostalAddressSameAsVisitationAddress  50373 non-null  bool
 59  ApprovalNumber                          0 non-null      object
 60  BrsNumber                               0 non-null      float64
 61  ChamberOfCommerceBranchNumber           1640 non-null   object
 62  IsCreditor                              50373 non-null  bool
 63  IsDebtor                                50373 non-null  bool
 64  OinNumber                               0 non-null      object
 65  UbnNumber                               0 non-null      float64
 66  VatNumber                               385 non-null    object
 67  ActiveExpansions                        27650 non-null  float64
 68  IsDeleted                               50373 non-null  bool
 69  IsDemo                                  50373 non-null  bool
dtypes: bool(6), float64(9), int64(3), object(52)
memory usage: 24.9+ MB

# Addresses

In [38]:
Addresses = get_table("Management", "Addresses")

In [39]:
Addresses.head()

,addresses_id,Street,HouseNumber,PostalCode,City,Country
0,4bd6ceae-cb86-48b0-8308-004c88a2b257,Elbe,2,7908 HB,Hoogeveen,NL
1,c0b3d3db-9821-4577-ba78-7c5ed7ca81da,Wapserveenseweg,26,7986 PH,Wittelte,NL
2,a1b3493f-ac09-46f2-bc17-fe4a8d898a9c,Bouwweg,14,8243 PJ,Lelystad,NL
3,baccad4d-7bc0-454e-9ead-fc36c96f0c04,Bouwweg,14,8243 PJ,Lelystad,NL
4,cb385056-679c-4794-8eeb-4e138de71618,Akkerdijk,1,7462 PP,Rijssen,NL

In [40]:
Addresses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73202 entries, 0 to 73201
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   addresses_id  73202 non-null  object
 1   Street        71960 non-null  object
 2   HouseNumber   71944 non-null  object
 3   PostalCode    71027 non-null  object
 4   City          71953 non-null  object
 5   Country       71991 non-null  object
dtypes: object(6)
memory usage: 3.4+ MB

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 70 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   orderservices_id                        50373 non-null  object
 1   OrderId                                 50373 non-null  object
 2   ServiceId                               50373 non-null  object
 3   orderservicesname                       50373 non-null  object
 4   DisplayPriority                         50373 non-null  float64
 5   ReferenceId                             50373 non-null  object
 6   orderserviceline_id                     50373 non-null  object
 7   OrderServiceId                          50373 non-null  object
 8   EmployeeId                              50373 non-null  object
 9   ServiceLineId_x                         50373 non-null  object
 10  orderservicelinename                    50373 non-null  object
 11  IsAttachment                            49463 non-null  object
 12  orders_id                               50373 non-null  object
 13  TenantId                                50373 non-null  object
 14  ClientId                                50373 non-null  object
 15  ContactId                               2171 non-null   object
 16  OrderStatus                             50373 non-null  int64
 17  Instructions                            4855 non-null   object
 18  ProjectId                               4850 non-null   object
 19  ContactSupplierId                       0 non-null      object
 20  ProjectSupplierId                       11 non-null     object
 21  SupplierId                              642 non-null    object
 22  Type                                    50373 non-null  float64
 23  AppointmentId                           0 non-null      object
 24  CompanyId                               50373 non-null  object
 25  CodePostfix                             50373 non-null  int64
 26  CodePrefix                              50373 non-null  int64
 27  CreatedByUserId                         50373 non-null  object
 28  Reference                               1579 non-null   object
 29  ServiceLineId_y                         49932 non-null  object
 30  UnitId                                  49932 non-null  float64
 31  Amount                                  49932 non-null  float64
 32  units_id                                49932 non-null  float64
 33  unitsname                               49932 non-null  object
 34  Code_x                                  49932 non-null  object
 35  IsoCode                                 49932 non-null  object
 36  EdiCode                                 49932 non-null  object
 37  IsArchived                              49932 non-null  object
 38  IsTime                                  49932 non-null  object
 39  IsAlwaysSelectable                      49932 non-null  object
 40  ServiceLineId                           17924 non-null  object
 41  EquipmentId                             17924 non-null  object
 42  EquipmentType                           17924 non-null  float64
 43  relations_id                            50373 non-null  object
 44  relationsname                           50373 non-null  object
 45  Code_y                                  50373 non-null  object
 46  Attention                               0 non-null      object
 47  ChamberOfCommerce                       50373 non-null  object
 48  Email                                   31267 non-null  object
 49  Infix                                   0 non-null      object
 50  Initials                                0 non-null      object
 51  MobilePhoneNumber                       19870 non-null  object
 52  PhoneNumber                             7798 non-null   object
 53  Prefixes                                0 non-null      object
 54  Website                                 8595 non-null   object
 55  PostalAddressId                         50363 non-null  object
 56  VisitationAddressId                     50373 non-null  object
 57  BlockUserLogins                         50373 non-null  bool
 58  IsPostalAddressSameAsVisitationAddress  50373 non-null  bool
 59  ApprovalNumber                          0 non-null      object
 60  BrsNumber                               0 non-null      float64
 61  ChamberOfCommerceBranchNumber           1640 non-null   object
 62  IsCreditor                              50373 non-null  bool
 63  IsDebtor                                50373 non-null  bool
 64  OinNumber                               0 non-null      object
 65  UbnNumber                               0 non-null      float64
 66  VatNumber                               385 non-null    object
 67  ActiveExpansions                        27650 non-null  float64
 68  IsDeleted                               50373 non-null  bool
 69  IsDemo                                  50373 non-null  bool
dtypes: bool(6), float64(9), int64(3), object(52)
memory usage: 24.9+ MB

# coords

In [42]:
Addresses.head()

,addresses_id,Street,HouseNumber,PostalCode,City,Country
0,4bd6ceae-cb86-48b0-8308-004c88a2b257,Elbe,2,7908 HB,Hoogeveen,NL
1,c0b3d3db-9821-4577-ba78-7c5ed7ca81da,Wapserveenseweg,26,7986 PH,Wittelte,NL
2,a1b3493f-ac09-46f2-bc17-fe4a8d898a9c,Bouwweg,14,8243 PJ,Lelystad,NL
3,baccad4d-7bc0-454e-9ead-fc36c96f0c04,Bouwweg,14,8243 PJ,Lelystad,NL
4,cb385056-679c-4794-8eeb-4e138de71618,Akkerdijk,1,7462 PP,Rijssen,NL

In [43]:
bag = pd.read_csv("bag_nederland_coords.csv")

In [44]:
bag.head()

             straat  hnr      pc      plaats        lat       lon
0          Steenweg  32A  6131BE     Sittard  50.999949  5.862879
1          Steenweg  32A  6131BE     Sittard  50.999949  5.862879
2          Steenweg  32A  6131BE     Sittard  50.999949  5.862879
3          Steenweg  32A  6131BE     Sittard  50.999949  5.862879
4  Snelgersmastraat  3-I  9901AA  Appingedam  53.319832  6.854126

In [45]:
bag = bag.drop_duplicates(subset=["pc"])

In [46]:
bag.head()

                 straat  hnr      pc      plaats        lat       lon
0              Steenweg  32A  6131BE     Sittard  50.999949  5.862879
4      Snelgersmastraat  3-I  9901AA  Appingedam  53.319832  6.854126
99   Bouwmeestersstraat    1  9901AB  Appingedam  53.320874  6.853486
120         Molenstraat    1  9901AC  Appingedam  53.320364  6.854775
147         Molenstraat    8  9901KB  Appingedam  53.321041  6.854732

In [47]:
Addresses["PostalCode"] = Addresses["PostalCode"].str.upper().str.replace(" ", "", regex=False)

In [48]:
Addresses = Addresses.merge(bag, left_on="PostalCode", right_on="pc", how="left")

In [49]:
Addresses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73202 entries, 0 to 73201
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   addresses_id  73202 non-null  object
 1   Street        71960 non-null  object
 2   HouseNumber   71944 non-null  object
 3   PostalCode    71027 non-null  object
 4   City          71953 non-null  object
 5   Country       71991 non-null  object
 6   straat        65714 non-null  object
 7   hnr           65714 non-null  object
 8   pc            65714 non-null  object
 9   plaats        65714 non-null  object
 10  lat           65714 non-null  float64
 11  lon           65714 non-null  float64
dtypes: float64(2), object(10)
memory usage: 6.7+ MB

In [50]:
df = df.merge(Addresses, left_on="PostalAddressId", right_on="addresses_id", how="left")

# Services

In [51]:
Services = get_table("Management", "Services")

In [52]:
Services.head()

,services_id,Code,servicesname,WorkType,PlanningGroupId,RevenueGroupId,IsLocationCompulsory,RelationId
0,97edce85-f832-44bf-8a17-73a29ef422c2,098,champost transport / containers,1,111,132,False,9c822f1c-e7d1-4dd7-b814-148ffce6cace
1,37c34f2f-90c6-4782-96bb-94f28a1d025c,3001,Grashakselen,1,5,5,True,a46b0d64-2b99-41a4-8137-0e589a9c246f
2,26175000-cb51-4263-80c2-49d2f73464c6,LB1004,Administratie,1,48,70,False,22c76114-3ea7-443d-abcd-02c890a9711e
3,57121f4d-3099-4d0e-a784-2caee3184e93,3201,Spuiten grasland,1,21,27,True,a46b0d64-2b99-41a4-8137-0e589a9c246f
4,2c7d8420-33a5-4f81-9d72-d7cc17f9d1de,LB1101,Afvoer spuitater bio.,1,41,64,False,22c76114-3ea7-443d-abcd-02c890a9711e

In [53]:
Services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4142 entries, 0 to 4141
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   services_id           4142 non-null   object
 1   Code                  4142 non-null   object
 2   servicesname          4142 non-null   object
 3   WorkType              4142 non-null   int64
 4   PlanningGroupId       4142 non-null   int64
 5   RevenueGroupId        4142 non-null   int64
 6   IsLocationCompulsory  4142 non-null   bool
 7   RelationId            4142 non-null   object
dtypes: bool(1), int64(3), object(4)
memory usage: 230.7+ KB

In [54]:
df = df.merge(
    Services, left_on=["TenantId", "ServiceId"], right_on=["RelationId", "services_id"], how="left"
)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 90 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   orderservices_id                        50373 non-null  object
 1   OrderId                                 50373 non-null  object
 2   ServiceId                               50373 non-null  object
 3   orderservicesname                       50373 non-null  object
 4   DisplayPriority                         50373 non-null  float64
 5   ReferenceId                             50373 non-null  object
 6   orderserviceline_id                     50373 non-null  object
 7   OrderServiceId                          50373 non-null  object
 8   EmployeeId                              50373 non-null  object
 9   ServiceLineId_x                         50373 non-null  object
 10  orderservicelinename                    50373 non-null  object
 11  IsAttachment                            49463 non-null  object
 12  orders_id                               50373 non-null  object
 13  TenantId                                50373 non-null  object
 14  ClientId                                50373 non-null  object
 15  ContactId                               2171 non-null   object
 16  OrderStatus                             50373 non-null  int64
 17  Instructions                            4855 non-null   object
 18  ProjectId                               4850 non-null   object
 19  ContactSupplierId                       0 non-null      object
 20  ProjectSupplierId                       11 non-null     object
 21  SupplierId                              642 non-null    object
 22  Type                                    50373 non-null  float64
 23  AppointmentId                           0 non-null      object
 24  CompanyId                               50373 non-null  object
 25  CodePostfix                             50373 non-null  int64
 26  CodePrefix                              50373 non-null  int64
 27  CreatedByUserId                         50373 non-null  object
 28  Reference                               1579 non-null   object
 29  ServiceLineId_y                         49932 non-null  object
 30  UnitId                                  49932 non-null  float64
 31  Amount                                  49932 non-null  float64
 32  units_id                                49932 non-null  float64
 33  unitsname                               49932 non-null  object
 34  Code_x                                  49932 non-null  object
 35  IsoCode                                 49932 non-null  object
 36  EdiCode                                 49932 non-null  object
 37  IsArchived                              49932 non-null  object
 38  IsTime                                  49932 non-null  object
 39  IsAlwaysSelectable                      49932 non-null  object
 40  ServiceLineId                           17924 non-null  object
 41  EquipmentId                             17924 non-null  object
 42  EquipmentType                           17924 non-null  float64
 43  relations_id                            50373 non-null  object
 44  relationsname                           50373 non-null  object
 45  Code_y                                  50373 non-null  object
 46  Attention                               0 non-null      object
 47  ChamberOfCommerce                       50373 non-null  object
 48  Email                                   31267 non-null  object
 49  Infix                                   0 non-null      object
 50  Initials                                0 non-null      object
 51  MobilePhoneNumber                       19870 non-null  object
 52  PhoneNumber                             7798 non-null   object
 53  Prefixes                                0 non-null      object
 54  Website                                 8595 non-null   object
 55  PostalAddressId                         50363 non-null  object
 56  VisitationAddressId                     50373 non-null  object
 57  BlockUserLogins                         50373 non-null  bool
 58  IsPostalAddressSameAsVisitationAddress  50373 non-null  bool
 59  ApprovalNumber                          0 non-null      object
 60  BrsNumber                               0 non-null      float64
 61  ChamberOfCommerceBranchNumber           1640 non-null   object
 62  IsCreditor                              50373 non-null  bool
 63  IsDebtor                                50373 non-null  bool
 64  OinNumber                               0 non-null      object
 65  UbnNumber                               0 non-null      float64
 66  VatNumber                               385 non-null    object
 67  ActiveExpansions                        27650 non-null  float64
 68  IsDeleted                               50373 non-null  bool
 69  IsDemo                                  50373 non-null  bool
 70  addresses_id                            50363 non-null  object
 71  Street                                  50140 non-null  object
 72  HouseNumber                             50140 non-null  object
 73  PostalCode                              50140 non-null  object
 74  City                                    50140 non-null  object
 75  Country                                 46830 non-null  object
 76  straat                                  50120 non-null  object
 77  hnr                                     50120 non-null  object
 78  pc                                      50120 non-null  object
 79  plaats                                  50120 non-null  object
 80  lat                                     50120 non-null  float64
 81  lon                                     50120 non-null  float64
 82  services_id                             49889 non-null  object
 83  Code                                    49889 non-null  object
 84  servicesname                            49889 non-null  object
 85  WorkType                                49889 non-null  float64
 86  PlanningGroupId                         49889 non-null  float64
 87  RevenueGroupId                          49889 non-null  float64
 88  IsLocationCompulsory                    49889 non-null  object
 89  RelationId                              49889 non-null  object
dtypes: bool(6), float64(14), int64(3), object(67)
memory usage: 32.6+ MB

# ServiceLines

In [56]:
ServiceLines = get_table("Management", "ServiceLines")

In [57]:
ServiceLines.head()

,servicelines_id,servicelinesname,ServiceId,OrderBy,ReferenceId,IsAttachment
0,88f603e0-a31c-471d-898b-5b79eddb56cf,Shovel 15ton,445e03b3-6495-410d-b314-1a91a4290905,0,bc446be7-cebd-8369-972f-0b954886a73a,False
1,acc35755-9fdf-415a-b021-f9355492b515,Mobiele kraan,ac110fde-81b0-4b37-9192-40ab4cc46f44,0,86429365-390e-73e4-75ee-e5e2f1c18d91,False
2,5326814c-8451-41ca-950f-0e9fc9987afe,Hakselaar + graspickup,37c34f2f-90c6-4782-96bb-94f28a1d025c,0,9812896b-488e-581b-bc9d-b5849bbab989,False
3,d70a79da-69e1-4412-9197-3efc552e2098,Trekker + silagewagen,37c34f2f-90c6-4782-96bb-94f28a1d025c,1,1a29489c-19dd-1fc7-865f-93884e865a10,False
4,6daba7b8-5851-4e3f-98a3-d853809d6184,Trekker + silagewagen,37c34f2f-90c6-4782-96bb-94f28a1d025c,2,5e75d999-739f-978d-34bb-b81434bde82d,False

In [58]:
ServiceLines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4437 entries, 0 to 4436
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   servicelines_id   4437 non-null   object
 1   servicelinesname  4437 non-null   object
 2   ServiceId         4437 non-null   object
 3   OrderBy           4437 non-null   int64
 4   ReferenceId       4437 non-null   object
 5   IsAttachment      2549 non-null   object
dtypes: int64(1), object(5)
memory usage: 208.1+ KB

In [59]:
df = df.merge(ServiceLines, left_on="ServiceLineId_x", right_on="servicelines_id", how="left")

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 96 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   orderservices_id                        50373 non-null  object
 1   OrderId                                 50373 non-null  object
 2   ServiceId_x                             50373 non-null  object
 3   orderservicesname                       50373 non-null  object
 4   DisplayPriority                         50373 non-null  float64
 5   ReferenceId_x                           50373 non-null  object
 6   orderserviceline_id                     50373 non-null  object
 7   OrderServiceId                          50373 non-null  object
 8   EmployeeId                              50373 non-null  object
 9   ServiceLineId_x                         50373 non-null  object
 10  orderservicelinename                    50373 non-null  object
 11  IsAttachment_x                          49463 non-null  object
 12  orders_id                               50373 non-null  object
 13  TenantId                                50373 non-null  object
 14  ClientId                                50373 non-null  object
 15  ContactId                               2171 non-null   object
 16  OrderStatus                             50373 non-null  int64
 17  Instructions                            4855 non-null   object
 18  ProjectId                               4850 non-null   object
 19  ContactSupplierId                       0 non-null      object
 20  ProjectSupplierId                       11 non-null     object
 21  SupplierId                              642 non-null    object
 22  Type                                    50373 non-null  float64
 23  AppointmentId                           0 non-null      object
 24  CompanyId                               50373 non-null  object
 25  CodePostfix                             50373 non-null  int64
 26  CodePrefix                              50373 non-null  int64
 27  CreatedByUserId                         50373 non-null  object
 28  Reference                               1579 non-null   object
 29  ServiceLineId_y                         49932 non-null  object
 30  UnitId                                  49932 non-null  float64
 31  Amount                                  49932 non-null  float64
 32  units_id                                49932 non-null  float64
 33  unitsname                               49932 non-null  object
 34  Code_x                                  49932 non-null  object
 35  IsoCode                                 49932 non-null  object
 36  EdiCode                                 49932 non-null  object
 37  IsArchived                              49932 non-null  object
 38  IsTime                                  49932 non-null  object
 39  IsAlwaysSelectable                      49932 non-null  object
 40  ServiceLineId                           17924 non-null  object
 41  EquipmentId                             17924 non-null  object
 42  EquipmentType                           17924 non-null  float64
 43  relations_id                            50373 non-null  object
 44  relationsname                           50373 non-null  object
 45  Code_y                                  50373 non-null  object
 46  Attention                               0 non-null      object
 47  ChamberOfCommerce                       50373 non-null  object
 48  Email                                   31267 non-null  object
 49  Infix                                   0 non-null      object
 50  Initials                                0 non-null      object
 51  MobilePhoneNumber                       19870 non-null  object
 52  PhoneNumber                             7798 non-null   object
 53  Prefixes                                0 non-null      object
 54  Website                                 8595 non-null   object
 55  PostalAddressId                         50363 non-null  object
 56  VisitationAddressId                     50373 non-null  object
 57  BlockUserLogins                         50373 non-null  bool
 58  IsPostalAddressSameAsVisitationAddress  50373 non-null  bool
 59  ApprovalNumber                          0 non-null      object
 60  BrsNumber                               0 non-null      float64
 61  ChamberOfCommerceBranchNumber           1640 non-null   object
 62  IsCreditor                              50373 non-null  bool
 63  IsDebtor                                50373 non-null  bool
 64  OinNumber                               0 non-null      object
 65  UbnNumber                               0 non-null      float64
 66  VatNumber                               385 non-null    object
 67  ActiveExpansions                        27650 non-null  float64
 68  IsDeleted                               50373 non-null  bool
 69  IsDemo                                  50373 non-null  bool
 70  addresses_id                            50363 non-null  object
 71  Street                                  50140 non-null  object
 72  HouseNumber                             50140 non-null  object
 73  PostalCode                              50140 non-null  object
 74  City                                    50140 non-null  object
 75  Country                                 46830 non-null  object
 76  straat                                  50120 non-null  object
 77  hnr                                     50120 non-null  object
 78  pc                                      50120 non-null  object
 79  plaats                                  50120 non-null  object
 80  lat                                     50120 non-null  float64
 81  lon                                     50120 non-null  float64
 82  services_id                             49889 non-null  object
 83  Code                                    49889 non-null  object
 84  servicesname                            49889 non-null  object
 85  WorkType                                49889 non-null  float64
 86  PlanningGroupId                         49889 non-null  float64
 87  RevenueGroupId                          49889 non-null  float64
 88  IsLocationCompulsory                    49889 non-null  object
 89  RelationId                              49889 non-null  object
 90  servicelines_id                         49708 non-null  object
 91  servicelinesname                        49708 non-null  object
 92  ServiceId_y                             49708 non-null  object
 93  OrderBy                                 49708 non-null  float64
 94  ReferenceId_y                           49708 non-null  object
 95  IsAttachment_y                          41001 non-null  object
dtypes: bool(6), float64(15), int64(3), object(72)
memory usage: 34.9+ MB

# Equipment

In [61]:
Equipment = get_table("Management", "Equipment")

In [62]:
Equipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2614 entries, 0 to 2613
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   equipment_id          2614 non-null   object
 1   Code                  2614 non-null   object
 2   equipmentname         2614 non-null   object
 3   EquipmentType         2614 non-null   int64
 4   Identifier            1261 non-null   object
 5   Photo                 0 non-null      object
 6   CargoVolume           67 non-null     float64
 7   Type                  6 non-null      float64
 8   PurchaseDate          1781 non-null   object
 9   SalesDate             2 non-null      datetime64[ns, UTC]
 10  TotalPrice            36 non-null     float64
 11  OwnerRelationId       2346 non-null   object
 12  PreferredEmployeeId   44 non-null     object
 13  PreferredImplementId  5 non-null      object
 14  PreferredMachineId    34 non-null     object
 15  RelationId            2614 non-null   object
 16  EmptyMass             129 non-null    float64
 17  PreferredServiceId    25 non-null     object
dtypes: datetime64[ns, UTC](1), float64(4), int64(1), object(12)
memory usage: 367.7+ KB

In [63]:
EquipmentToEquipmentGroups = get_table("Management", "EquipmentToEquipmentGroups")

In [64]:
EquipmentGroups = get_table("Management", "EquipmentGroups")

In [65]:
EquipmentGroups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   equipmentgroups_id   398 non-null    int64
 1   Code                 398 non-null    object
 2   equipmentgroupsname  398 non-null    object
 3   RelationId           398 non-null    object
 4   EquipmentGroupTypes  398 non-null    int64
dtypes: int64(2), object(3)
memory usage: 15.7+ KB

In [66]:
Equipment = Equipment.merge(
    EquipmentToEquipmentGroups, left_on="equipment_id", right_on="EquipmentId", how="left"
)

In [67]:
EquipmentGroups = EquipmentGroups.drop(columns=["RelationId"])

In [68]:
Equipment = Equipment.merge(
    EquipmentGroups, left_on="EquipmentGroupId", right_on="equipmentgroups_id", how="left"
)

In [69]:
Equipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2649 entries, 0 to 2648
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   equipment_id          2649 non-null   object
 1   Code_x                2649 non-null   object
 2   equipmentname         2649 non-null   object
 3   EquipmentType         2649 non-null   int64
 4   Identifier            1282 non-null   object
 5   Photo                 0 non-null      object
 6   CargoVolume           68 non-null     float64
 7   Type                  6 non-null      float64
 8   PurchaseDate          1803 non-null   object
 9   SalesDate             2 non-null      datetime64[ns, UTC]
 10  TotalPrice            37 non-null     float64
 11  OwnerRelationId       2379 non-null   object
 12  PreferredEmployeeId   44 non-null     object
 13  PreferredImplementId  6 non-null      object
 14  PreferredMachineId    34 non-null     object
 15  RelationId            2649 non-null   object
 16  EmptyMass             131 non-null    float64
 17  PreferredServiceId    26 non-null     object
 18  EquipmentId           2393 non-null   object
 19  EquipmentGroupId      2393 non-null   float64
 20  equipmentgroups_id    2393 non-null   float64
 21  Code_y                2393 non-null   object
 22  equipmentgroupsname   2393 non-null   object
 23  EquipmentGroupTypes   2393 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(7), int64(1), object(15)
memory usage: 496.8+ KB

In [70]:
Equipment.head()

,equipment_id,Code_x,equipmentname,EquipmentType,Identifier,Photo,CargoVolume,Type,PurchaseDate,SalesDate,...,PreferredMachineId,RelationId,EmptyMass,PreferredServiceId,EquipmentId,EquipmentGroupId,equipmentgroups_id,Code_y,equipmentgroupsname,EquipmentGroupTypes
0,242af3c1-6a40-4ed2-829b-fbcd030141fd,202010,Sleepslang pomp + Aanhanger,2,None,None,NaN,NaN,None,NaT,...,f7bb5b09-d1b1-4813-9d01-74673a4c0272,f5ab1b29-de37-4818-bb05-b2fe57ce6768,NaN,None,242af3c1-6a40-4ed2-829b-fbcd030141fd,181.0,181.0,08,Bemesting,2.0
1,f8fb7c04-d1d8-4bc6-94a8-4a8bf6436d92,100101,John Deere 6155R,1,TLR-93-Z,None,NaN,NaN,None,NaT,...,None,f5ab1b29-de37-4818-bb05-b2fe57ce6768,NaN,None,f8fb7c04-d1d8-4bc6-94a8-4a8bf6436d92,174.0,174.0,01,Trekkers,1.0
2,c5389e13-307d-45f5-9159-d5e832a43ac4,T1,VALTRA N174,1,T76GGL,None,NaN,NaN,2024-11-20 01:00:00+01:00,NaT,...,None,b7f10927-7343-4d0d-b157-43c7097476f3,NaN,None,c5389e13-307d-45f5-9159-d5e832a43ac4,211.0,211.0,T,Trekker,1.0
3,1d9183ea-09fa-4ddc-aede-2f61df58c600,KM1,Kunstmeststrooier,2,None,None,NaN,NaN,None,NaT,...,None,b7f10927-7343-4d0d-b157-43c7097476f3,NaN,None,1d9183ea-09fa-4ddc-aede-2f61df58c600,215.0,215.0,GR,Grondbewerking,2.0
4,a9ea18cc-3d56-44f2-9139-97ff96f9fa40,KI1,Kilverbak,2,None,None,NaN,NaN,None,NaT,...,None,b7f10927-7343-4d0d-b157-43c7097476f3,NaN,None,a9ea18cc-3d56-44f2-9139-97ff96f9fa40,215.0,215.0,GR,Grondbewerking,2.0

In [71]:
Equipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2649 entries, 0 to 2648
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   equipment_id          2649 non-null   object
 1   Code_x                2649 non-null   object
 2   equipmentname         2649 non-null   object
 3   EquipmentType         2649 non-null   int64
 4   Identifier            1282 non-null   object
 5   Photo                 0 non-null      object
 6   CargoVolume           68 non-null     float64
 7   Type                  6 non-null      float64
 8   PurchaseDate          1803 non-null   object
 9   SalesDate             2 non-null      datetime64[ns, UTC]
 10  TotalPrice            37 non-null     float64
 11  OwnerRelationId       2379 non-null   object
 12  PreferredEmployeeId   44 non-null     object
 13  PreferredImplementId  6 non-null      object
 14  PreferredMachineId    34 non-null     object
 15  RelationId            2649 non-null   object
 16  EmptyMass             131 non-null    float64
 17  PreferredServiceId    26 non-null     object
 18  EquipmentId           2393 non-null   object
 19  EquipmentGroupId      2393 non-null   float64
 20  equipmentgroups_id    2393 non-null   float64
 21  Code_y                2393 non-null   object
 22  equipmentgroupsname   2393 non-null   object
 23  EquipmentGroupTypes   2393 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(7), int64(1), object(15)
memory usage: 496.8+ KB

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50373 entries, 0 to 50372
Data columns (total 96 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   orderservices_id                        50373 non-null  object
 1   OrderId                                 50373 non-null  object
 2   ServiceId_x                             50373 non-null  object
 3   orderservicesname                       50373 non-null  object
 4   DisplayPriority                         50373 non-null  float64
 5   ReferenceId_x                           50373 non-null  object
 6   orderserviceline_id                     50373 non-null  object
 7   OrderServiceId                          50373 non-null  object
 8   EmployeeId                              50373 non-null  object
 9   ServiceLineId_x                         50373 non-null  object
 10  orderservicelinename                    50373 non-null  object
 11  IsAttachment_x                          49463 non-null  object
 12  orders_id                               50373 non-null  object
 13  TenantId                                50373 non-null  object
 14  ClientId                                50373 non-null  object
 15  ContactId                               2171 non-null   object
 16  OrderStatus                             50373 non-null  int64
 17  Instructions                            4855 non-null   object
 18  ProjectId                               4850 non-null   object
 19  ContactSupplierId                       0 non-null      object
 20  ProjectSupplierId                       11 non-null     object
 21  SupplierId                              642 non-null    object
 22  Type                                    50373 non-null  float64
 23  AppointmentId                           0 non-null      object
 24  CompanyId                               50373 non-null  object
 25  CodePostfix                             50373 non-null  int64
 26  CodePrefix                              50373 non-null  int64
 27  CreatedByUserId                         50373 non-null  object
 28  Reference                               1579 non-null   object
 29  ServiceLineId_y                         49932 non-null  object
 30  UnitId                                  49932 non-null  float64
 31  Amount                                  49932 non-null  float64
 32  units_id                                49932 non-null  float64
 33  unitsname                               49932 non-null  object
 34  Code_x                                  49932 non-null  object
 35  IsoCode                                 49932 non-null  object
 36  EdiCode                                 49932 non-null  object
 37  IsArchived                              49932 non-null  object
 38  IsTime                                  49932 non-null  object
 39  IsAlwaysSelectable                      49932 non-null  object
 40  ServiceLineId                           17924 non-null  object
 41  EquipmentId                             17924 non-null  object
 42  EquipmentType                           17924 non-null  float64
 43  relations_id                            50373 non-null  object
 44  relationsname                           50373 non-null  object
 45  Code_y                                  50373 non-null  object
 46  Attention                               0 non-null      object
 47  ChamberOfCommerce                       50373 non-null  object
 48  Email                                   31267 non-null  object
 49  Infix                                   0 non-null      object
 50  Initials                                0 non-null      object
 51  MobilePhoneNumber                       19870 non-null  object
 52  PhoneNumber                             7798 non-null   object
 53  Prefixes                                0 non-null      object
 54  Website                                 8595 non-null   object
 55  PostalAddressId                         50363 non-null  object
 56  VisitationAddressId                     50373 non-null  object
 57  BlockUserLogins                         50373 non-null  bool
 58  IsPostalAddressSameAsVisitationAddress  50373 non-null  bool
 59  ApprovalNumber                          0 non-null      object
 60  BrsNumber                               0 non-null      float64
 61  ChamberOfCommerceBranchNumber           1640 non-null   object
 62  IsCreditor                              50373 non-null  bool
 63  IsDebtor                                50373 non-null  bool
 64  OinNumber                               0 non-null      object
 65  UbnNumber                               0 non-null      float64
 66  VatNumber                               385 non-null    object
 67  ActiveExpansions                        27650 non-null  float64
 68  IsDeleted                               50373 non-null  bool
 69  IsDemo                                  50373 non-null  bool
 70  addresses_id                            50363 non-null  object
 71  Street                                  50140 non-null  object
 72  HouseNumber                             50140 non-null  object
 73  PostalCode                              50140 non-null  object
 74  City                                    50140 non-null  object
 75  Country                                 46830 non-null  object
 76  straat                                  50120 non-null  object
 77  hnr                                     50120 non-null  object
 78  pc                                      50120 non-null  object
 79  plaats                                  50120 non-null  object
 80  lat                                     50120 non-null  float64
 81  lon                                     50120 non-null  float64
 82  services_id                             49889 non-null  object
 83  Code                                    49889 non-null  object
 84  servicesname                            49889 non-null  object
 85  WorkType                                49889 non-null  float64
 86  PlanningGroupId                         49889 non-null  float64
 87  RevenueGroupId                          49889 non-null  float64
 88  IsLocationCompulsory                    49889 non-null  object
 89  RelationId                              49889 non-null  object
 90  servicelines_id                         49708 non-null  object
 91  servicelinesname                        49708 non-null  object
 92  ServiceId_y                             49708 non-null  object
 93  OrderBy                                 49708 non-null  float64
 94  ReferenceId_y                           49708 non-null  object
 95  IsAttachment_y                          41001 non-null  object
dtypes: bool(6), float64(15), int64(3), object(72)
memory usage: 34.9+ MB

In [73]:
df = df.merge(Equipment, left_on="EquipmentId", right_on="equipment_id", how="left")

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50819 entries, 0 to 50818
Columns: 120 entries, orderservices_id to EquipmentGroupTypes
dtypes: bool(6), datetime64[ns, UTC](1), float64(23), int64(3), object(87)
memory usage: 44.5+ MB

# PlanningGroups

In [75]:
PlanningGroups = get_table("Management", "PlanningGroups")

In [76]:
PlanningGroups.head()

,planninggroups_id,planninggroupsname,RelationId,Color
0,1,Shovels,a46b0d64-2b99-41a4-8137-0e589a9c246f,#f5d90a
1,2,Mobiele kranen,a46b0d64-2b99-41a4-8137-0e589a9c246f,#588ac7
2,3,Rupskranen,a46b0d64-2b99-41a4-8137-0e589a9c246f,#2c4db8
3,4,Minikranen,a46b0d64-2b99-41a4-8137-0e589a9c246f,#6bc7d1
4,5,Oogst,a46b0d64-2b99-41a4-8137-0e589a9c246f,#2e8f41

In [77]:
PlanningGroups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 425 entries, 0 to 424
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   planninggroups_id   425 non-null    int64
 1   planninggroupsname  425 non-null    object
 2   RelationId          425 non-null    object
 3   Color               425 non-null    object
dtypes: int64(1), object(3)
memory usage: 13.4+ KB

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50819 entries, 0 to 50818
Columns: 120 entries, orderservices_id to EquipmentGroupTypes
dtypes: bool(6), datetime64[ns, UTC](1), float64(23), int64(3), object(87)
memory usage: 44.5+ MB

In [79]:
df = df.merge(PlanningGroups, left_on="PlanningGroupId", right_on="planninggroups_id", how="left")

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50819 entries, 0 to 50818
Columns: 124 entries, orderservices_id to Color
dtypes: bool(6), datetime64[ns, UTC](1), float64(24), int64(3), object(90)
memory usage: 46.0+ MB

# TimeRegistration

In [81]:
TimeRegistration = get_table("Orders", "TimeRegistration")

In [82]:
TimeRegistration.head()

,timeregistration_id,EmployeeId,TimeTypeId,StartTime,EndTime,Duration,OrderId,Status,TenantId,ManHourDuration
0,e75dcb5a-024d-43aa-b287-7b5f567e8c4c,76b2f19b-fa3d-463f-b17c-9f11830cb44b,1,2024-04-12 13:49:40.603000+02:00,2024-04-12 13:49:40.603000+02:00,0.00,7607a38a-1e6a-4ba2-b885-928d0f59243e,1,a46b0d64-2b99-41a4-8137-0e589a9c246f,NaN
1,703f3222-4043-40be-8689-98701e2d2675,1341a8b0-45ad-4967-affc-c758ce49429a,37,2024-11-12 15:15:00+01:00,2024-11-12 15:25:00+01:00,0.17,8fe98598-4ee4-43cb-b040-d4b93a42b353,1,9c12160d-de6f-4d89-9ff5-3ab797cbd8b7,NaN
2,519755a7-ed99-492d-a6ae-57a5d0007ade,ebf7de4e-ba51-480a-86db-7b9473faa6c2,37,2024-09-20 10:00:00+02:00,2024-09-20 10:15:00+02:00,0.25,624bfd3a-01f5-4f9e-9b3c-5ba7f8c49940,2,9c12160d-de6f-4d89-9ff5-3ab797cbd8b7,NaN
3,94444d9e-7943-46d1-84e9-aeb96c6552f1,1341a8b0-45ad-4967-affc-c758ce49429a,36,2024-11-12 15:00:00+01:00,2024-11-12 16:00:00+01:00,1.00,8fe98598-4ee4-43cb-b040-d4b93a42b353,1,9c12160d-de6f-4d89-9ff5-3ab797cbd8b7,0.833333
4,55fca8f6-9539-44fe-9044-4c8f0ab59eca,8ce44d18-4b2a-4564-ae75-39ab03024406,13,2024-07-16 17:16:41+02:00,None,0.00,5035504c-322a-4aa4-a2ec-b7dab5684f3c,1,89c40dca-4cac-4b9d-9636-951596393ede,NaN

In [83]:
TimeRegistration.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35977 entries, 0 to 35976
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timeregistration_id  35977 non-null  object
 1   EmployeeId           35977 non-null  object
 2   TimeTypeId           35977 non-null  int64
 3   StartTime            35977 non-null  object
 4   EndTime              34685 non-null  object
 5   Duration             35977 non-null  float64
 6   OrderId              35882 non-null  object
 7   Status               35977 non-null  int64
 8   TenantId             35977 non-null  object
 9   ManHourDuration      23570 non-null  float64
dtypes: float64(2), int64(2), object(6)
memory usage: 2.7+ MB

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50819 entries, 0 to 50818
Columns: 124 entries, orderservices_id to Color
dtypes: bool(6), datetime64[ns, UTC](1), float64(24), int64(3), object(90)
memory usage: 46.0+ MB

In [85]:
df = df.merge(TimeRegistration, on=["OrderId", "EmployeeId"], how="left")

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67421 entries, 0 to 67420
Columns: 132 entries, orderservices_id to ManHourDuration
dtypes: bool(6), datetime64[ns, UTC](1), float64(28), int64(3), object(94)
memory usage: 65.2+ MB

In [87]:
df["StartTime"] = pd.to_datetime(df["StartTime"], utc=True, errors="coerce")

In [88]:
df["Datum"] = df["StartTime"].dt.date

In [89]:
df.head()

,orderservices_id,OrderId,ServiceId_x,orderservicesname,DisplayPriority,ReferenceId_x,orderserviceline_id,OrderServiceId,EmployeeId,ServiceLineId_x,...,Color,timeregistration_id,TimeTypeId,StartTime,EndTime,Duration,Status,TenantId_y,ManHourDuration,Datum
0,d395a0b0-df98-4a98-9a90-2111c573d171,64412a28-f398-44bb-b152-42bda916cc8f,887b1936-c9ea-4c1d-a82c-84fcd8f19e24,Kuhn ronde balen pers incl. wik. 6 lagen,0.0,ef334383-e743-4938-bb43-bf860d5e7b11,46063b18-b46f-42fe-91ba-f1edb5875ac2,d395a0b0-df98-4a98-9a90-2111c573d171,f140f35a-3bce-429a-83c7-62a740a01f9a,bce95084-2607-4ee2-977f-4e778e0852f4,...,#27cc77,ec231b02-85bf-42c8-9619-15a16fcf4c5e,25.0,2024-07-29 16:15:00+00:00,2024-07-29 19:10:00+02:00,0.92,2.0,47e405ef-a15f-40bc-be06-a33199799b12,0.916667,2024-07-29
1,d395a0b0-df98-4a98-9a90-2111c573d171,64412a28-f398-44bb-b152-42bda916cc8f,887b1936-c9ea-4c1d-a82c-84fcd8f19e24,Kuhn ronde balen pers incl. wik. 6 lagen,0.0,ef334383-e743-4938-bb43-bf860d5e7b11,46063b18-b46f-42fe-91ba-f1edb5875ac2,d395a0b0-df98-4a98-9a90-2111c573d171,f140f35a-3bce-429a-83c7-62a740a01f9a,bce95084-2607-4ee2-977f-4e778e0852f4,...,#27cc77,ec231b02-85bf-42c8-9619-15a16fcf4c5e,25.0,2024-07-29 16:15:00+00:00,2024-07-29 19:10:00+02:00,0.92,2.0,47e405ef-a15f-40bc-be06-a33199799b12,0.916667,2024-07-29
2,c8fcc1b7-25f6-4d34-8e22-3ba7cdeaa378,ac342819-3526-47bb-9c92-81e367c5ae99,0b435474-e59f-4a34-b5fe-0d5ff3ebafab,Kraan,1.0,0444bb78-9069-6409-9958-962f4dde2afb,1c062078-cf15-4b39-b958-372f5065f6d1,c8fcc1b7-25f6-4d34-8e22-3ba7cdeaa378,00000000-0000-0000-0000-000000000000,1a3c0309-4c64-4c65-b71b-91bf7b1412c5,...,#709e85,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT
3,96056b77-15d5-4d52-b8dc-fee6a5c3fe61,f15d47ea-25eb-4a45-8731-b90ab0552adb,36c94014-4cd2-483a-a59a-ad52263468ef,Mobiele Kraan,1.0,5ac1e343-d77a-8dbc-beb9-8d94347aae36,56928478-db32-4d47-aa5e-ff93ec216de2,96056b77-15d5-4d52-b8dc-fee6a5c3fe61,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,ddfc6777-8d48-426d-be11-70b464421688,...,#588ac7,b880fa84-6efe-4dbf-bbbe-188bafc795f9,1.0,2024-07-24 05:00:00+00:00,2024-07-24 16:00:00+02:00,9.00,1.0,39bf3eb6-b8c2-4832-8f92-d89e9e58ac38,0.000000,2024-07-24
4,c6021691-8aff-4a4e-af17-85381e7bde9a,8b7d46f6-1718-45a6-a296-e896a93e13e6,6be0ed95-3006-44f5-b00b-27fdc15ca5e6,Drijfmest met sleepslang,0.0,38867f22-08ae-453b-aba0-050e487ad825,83ce6728-df33-4478-98e1-88f5203cb6e1,c6021691-8aff-4a4e-af17-85381e7bde9a,8ce44d18-4b2a-4564-ae75-39ab03024406,66572589-bcc2-4bc0-8352-bac80524977c,...,#b03333,b87ec712-0604-4f08-b7c2-5a968f8133fb,13.0,2025-02-21 07:00:00+00:00,2025-02-21 11:15:00+01:00,3.25,2.0,89c40dca-4cac-4b9d-9636-951596393ede,3.250000,2025-02-21

# filter

In [90]:
df = df[df["OrderStatus"].isin([5, 7, 8, 9, 10])]

In [91]:
df = df[~df["timeregistration_id"].isna()]

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49081 entries, 0 to 67419
Columns: 133 entries, orderservices_id to Datum
dtypes: bool(6), datetime64[ns, UTC](2), float64(28), int64(3), object(94)
memory usage: 48.2+ MB

In [93]:
grouped = df.groupby(["EmployeeId"])["ManHourDuration"]

In [94]:
df["med_gem_tijd"] = grouped.expanding().mean().shift(1).reset_index(level=[0, 1], drop=True)
df["med_std_tijd"] = grouped.expanding().std().shift(1).reset_index(level=[0, 1], drop=True)
df["med_aantal_opdrachten"] = (
    grouped.expanding().count().shift(1).reset_index(level=[0, 1], drop=True)
)

In [95]:
df["taak_gem"] = (
    df.groupby(["ServiceId_x"])["ManHourDuration"]
    .expanding()
    .mean()
    .shift(1)
    .reset_index(level=[0, 1], drop=True)
)

In [96]:
ervaring = df.groupby(["EmployeeId", "ServiceId_x"]).cumcount()
df["med_ervaring_bewerking"] = ervaring

In [97]:
df = df.sort_values("Datum")

In [98]:
df["med_klant_bezoeken"] = df.groupby(["EmployeeId", "ClientId"]).cumcount()

In [99]:
df["med_totaal_opdrachten"] = df.groupby(["EmployeeId"]).cumcount()

In [100]:
df["med_klant_ratio"] = df["med_klant_bezoeken"] / (df["med_totaal_opdrachten"] + 1)

In [101]:
df["med_klant_gem_tijd"] = (
    df.groupby(["EmployeeId", "ClientId"])["ManHourDuration"]
    .expanding()
    .mean()
    .shift(1)
    .reset_index(level=[0, 1, 2], drop=True)
)

In [102]:
df["med_klant_snelheid"] = (
    (df["med_klant_gem_tijd"] / df["med_gem_tijd"].replace(0, np.nan)).fillna(1.0).clip(0.1, 5.0)
)

In [103]:
df["med_bewerking_gem_tijd"] = (
    df.groupby(["EmployeeId", "ServiceId_x"])["ManHourDuration"]
    .expanding()
    .mean()
    .shift(1)
    .reset_index(level=[0, 1, 2], drop=True)
)

In [104]:
df["med_bewerking_snelheid"] = (
    (df["med_bewerking_gem_tijd"] / df["med_gem_tijd"].replace(0, np.nan))
    .fillna(1.0)
    .clip(0.1, 5.0)
)

In [105]:
df["Datum"] = pd.to_datetime(df["Datum"])

In [106]:
df["dag_van_week"] = df["Datum"].dt.dayofweek
df["maand"] = df["Datum"].dt.month
df["week"] = df["Datum"].dt.isocalendar().week

In [107]:
df["week_sin"] = np.sin(2 * np.pi * df["week"] / 52)
df["week_cos"] = np.cos(2 * np.pi * df["week"] / 52)
df["dag_sin"] = np.sin(2 * np.pi * df["dag_van_week"] / 7)
df["dag_cos"] = np.cos(2 * np.pi * df["dag_van_week"] / 7)
df["maand_sin"] = np.sin(2 * np.pi * df["maand"] / 12)
df["maand_cos"] = np.cos(2 * np.pi * df["maand"] / 12)

In [108]:
top10 = (
    df.groupby("orderserviceline_id")["UnitId"]
    .nunique()
    .sort_values(ascending=False)
    .head(20)
    .index
)

df[df["orderserviceline_id"].isin(top10)].groupby("orderserviceline_id").agg(
    unique_units=("UnitId", "nunique"), unit_names=("unitsname", set)
).sort_values("unique_units", ascending=False)

,unique_units,unit_names
orderserviceline_id,,
afd41d14-51bf-4650-b24e-16b93a1bb2f6,4,"{Keer, Hectare, Uur, Stuk}"
1a48488a-342c-4d65-a00c-f1c09046ea7b,4,"{Keer, Ton, Uur, Kubieke meter}"
221d8b69-304c-1b2e-b7c5-7adc34ce89bd,4,"{Keer, Ton, Uur, Kubieke meter}"
e7c4310f-5dad-4939-8c38-2f4025103f7e,4,"{Keer, Hectare, Uur, Stuk}"
763ed2c0-4b5a-4a04-af47-b525246ecb15,4,"{Keer, Hectare, Uur, Stuk}"
85ea0606-ed4b-4bb9-8302-5a15cf192c51,4,"{Stuk, Hectare, Uur, Keer}"
1259186f-0836-4872-826b-dc3b4f2292fe,4,"{Keer, Ton, Uur, Kubieke meter}"
bdf566c5-2c36-43e9-a4d4-b364f0f05ce7,4,"{Stuk, Hectare, Uur, Keer}"
0ca0dc76-4544-4788-a8e7-ee47c8a761c2,3,"{Ton, Uur, Kubieke meter}"
f4983db8-4245-4339-a837-23d87f728069,3,"{Hectare, Uur, Kubieke meter}"
f4975781-ecda-4be0-8009-0115f0d1af20,3,"{Hectare, Uur, Kubieke meter}"
d4632ad2-ff9f-447a-80c6-5e283e1239ec,3,"{Hectare, Uur, Kubieke meter}"
a67b53f5-2512-4862-970a-7aeb50273336,3,"{Ton, Uur, Kubieke meter}"
a7175ee0-fc25-4814-b450-86cc641e5102,3,"{Hectare, Uur, Kubieke meter}"
a70f008a-6845-4dae-a4ed-934218a1beee,3,"{Hectare, Uur, Kubieke meter}"
7c727efd-0917-4122-ae0c-c5f68ce30873,3,"{Hectare, Uur, Kubieke meter}"
608f70bf-3fef-45ef-b451-5714759a15a8,3,"{Hectare, Uur, Kubieke meter}"
60181fb3-ca9d-41cd-9012-a8b78b9b162f,3,"{Ton, Uur, Kubieke meter}"
2ffe02e3-3c27-4da8-a124-bf04227c441b,3,"{Hectare, Uur, Kubieke meter}"
f4c234b6-fe82-4805-a157-d0e240eb4011,3,"{Hectare, Uur, Kubieke meter}"

In [109]:
# Pivot alle units naar kolommen
pivot = df.groupby(["orderserviceline_id", "unitsname"])["Amount"].sum().unstack(fill_value=0)

pivot.columns = [f"hoeveelheid_{col.lower().replace(' ', '_')}" for col in pivot.columns]
pivot = pivot.reset_index()

# Houd alleen de Uur rijen uit de originele df
df_uur = df[df["unitsname"] == "Uur"].drop_duplicates("orderserviceline_id")

# Merge de pivot kolommen erbij
df = df_uur.merge(pivot, on="orderserviceline_id", how="inner")

In [110]:
hoeveelheid_cols = [
    "hoeveelheid_baal",
    "hoeveelheid_big_bag",
    "hoeveelheid_dag",
    "hoeveelheid_hectare",
    "hoeveelheid_kubieke_meter",
    "hoeveelheid_meter",
    "hoeveelheid_milimeter",
    "hoeveelheid_stuk",
    "hoeveelheid_ton",
]

available_hoeveelheid_cols = [c for c in hoeveelheid_cols if c in df.columns]
missing_hoeveelheid_cols = [c for c in hoeveelheid_cols if c not in df.columns]

if missing_hoeveelheid_cols:
    print(f"Missing hoeveelheid columns treated as 0: {missing_hoeveelheid_cols}")

if available_hoeveelheid_cols:
    df["heeft_extra_eenheid"] = df[available_hoeveelheid_cols].fillna(0).sum(axis=1) > 0
else:
    df["heeft_extra_eenheid"] = False

Missing hoeveelheid columns treated as 0: ['hoeveelheid_big_bag', 'hoeveelheid_milimeter']

In [111]:
print(hoeveelheid_cols)

['hoeveelheid_baal', 'hoeveelheid_big_bag', 'hoeveelheid_dag', 'hoeveelheid_hectare', 'hoeveelheid_kubieke_meter', 'hoeveelheid_meter', 'hoeveelheid_milimeter', 'hoeveelheid_stuk', 'hoeveelheid_ton']

In [112]:
df.head()

,orderservices_id,OrderId,ServiceId_x,orderservicesname,DisplayPriority,ReferenceId_x,orderserviceline_id,OrderServiceId,EmployeeId,ServiceLineId_x,...,hoeveelheid_meter,hoeveelheid_roe,hoeveelheid_rol,hoeveelheid_stuk,hoeveelheid_ton,hoeveelheid_uur,hoeveelheid_vierkante_meter,hoeveelheid_vracht,hoeveelheid_week,heeft_extra_eenheid
0,0d928211-4e89-4e41-094b-d578addcc699,8dbb3f7f-5573-4e9d-992b-74c1735edbc2,c4448b2b-eccb-4a26-a210-3a554241e039,Reisuren met personenauto na 1-ste uur per dag,2.0,3bd9758a-a3cd-b1ce-a6b4-723a269625ea,221afda8-5e02-1cf6-50b9-96d3c1bc6777,0d928211-4e89-4e41-094b-d578addcc699,83292b27-3ebc-4ea6-92e7-4828aef27ea2,ea4d8d5d-3e71-4af0-8a11-d162eb7e9c01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
1,cc3f00c7-a7af-a0b9-32c6-3e87ab80f590,8dbb3f7f-5573-4e9d-992b-74c1735edbc2,41f494fc-00c9-4153-89ef-165612d292ab,Mobiele kraan Volvo EWR150E + Dr / Ka MT,1.0,b5a6cf68-61c6-58eb-21c5-f33ba50714c7,835c82f1-99a3-67c3-d67b-8de0b95aa15a,cc3f00c7-a7af-a0b9-32c6-3e87ab80f590,83292b27-3ebc-4ea6-92e7-4828aef27ea2,8b5398bf-050e-4e62-a28e-6bd2b5010c54,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
2,ee532c3b-0113-4ecd-95c7-f94d9613e59f,9387ce74-7cc1-423d-b9d4-9c282249e721,6778627f-7847-4824-bdb6-3df857ca36ba,Trekker + Dumper,1.0,00000000-0000-0000-0000-000000000000,a594b188-fd5d-4121-a627-aaac7f545b5b,ee532c3b-0113-4ecd-95c7-f94d9613e59f,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,a0814cd9-2736-4f62-9af3-8742538b0b46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
3,8329824a-f891-4189-9b38-2f705c9444c2,cf133289-e2f8-40b5-be3a-49393139241d,7063005d-ab68-4453-bb09-412135d9cdd1,Grasland bemesten,1.0,00000000-0000-0000-0000-000000000000,1cb43320-483c-4801-9ee5-01bc341ee9fe,8329824a-f891-4189-9b38-2f705c9444c2,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,710359a1-420c-4c0a-8d88-567bb3d364d3,...,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,False
4,60d49099-c502-47c8-a7a1-43caf71fbe31,62a29722-701a-4241-9101-83d037989573,159529a4-8319-4fcd-a831-e0a2cb2ef274,Gras zaaien,0.0,5d945d40-e5b2-4ff9-a703-29651c7266bd,a0372f4f-bc84-4e76-99c5-350685b91a8c,60d49099-c502-47c8-a7a1-43caf71fbe31,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,e2253dd7-b70c-4946-bf22-0d1e4523904e,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True

In [113]:
df.columns.to_series().to_csv("columns_rister.csv", index=False)

In [114]:
best_columns = [
    # IDs voor embeddings
    "EmployeeId",
    "ServiceLineId_x",
    "PlanningGroupId",
    "EquipmentGroupId",
    "ClientId",
    "TenantId_x",
    # Taak info
    "orderserviceline_id",
    "servicelinesname",
    "equipmentname",
    "EquipmentType_y",
    "EquipmentGroupTypes",
    "planninggroupsname",
    # Locatie
    "PostalCode",
    "lat",
    "lon",
    # Tijd
    "StartTime",
    "Datum",
    "dag_sin",
    "dag_cos",
    "maand_sin",
    "maand_cos",
    "week_sin",
    "week_cos",
    # Medewerker historiek
    "med_gem_tijd",
    "med_std_tijd",
    "med_aantal_opdrachten",
    "med_ervaring_bewerking",
    "taak_gem",
    "med_klant_bezoeken",
    "med_klant_ratio",
    "med_klant_snelheid",
    "med_bewerking_snelheid",
    "med_klant_gem_tijd",
    "med_bewerking_gem_tijd",
    "med_totaal_opdrachten",
    # Hoeveelheden
    "hoeveelheid_baal",
    "hoeveelheid_big_bag",
    "hoeveelheid_dag",
    "hoeveelheid_hectare",
    "hoeveelheid_kubieke_meter",
    "hoeveelheid_meter",
    "hoeveelheid_milimeter",
    "hoeveelheid_stuk",
    "hoeveelheid_ton",
    "heeft_extra_eenheid",
    # Target
    "hoeveelheid_uur",
]

In [115]:
missing_best_columns = [c for c in best_columns if c not in df.columns]
if missing_best_columns:
    print(f"Missing best_columns skipped: {missing_best_columns}")

best_columns = [c for c in best_columns if c in df.columns]
df = df[best_columns]

Missing best_columns skipped: ['hoeveelheid_big_bag', 'hoeveelheid_milimeter']

In [116]:
df["hoeveelheid_uur"].describe()

count    23434.000000
mean         7.819922
std          9.201982
min       -111.000000
25%          1.250000
50%          4.500000
75%         12.000000
max        146.040000
Name: hoeveelheid_uur, dtype: float64

In [117]:
# drop rows with hoeveelheid_uur <= 0
df = df[df["hoeveelheid_uur"] > 0]

In [118]:
grens = df["hoeveelheid_uur"].quantile(0.99)
df = df[df["hoeveelheid_uur"] <= grens]

In [119]:
df["hoeveelheid_uur"].describe().transpose()

count    19948.000000
mean         8.661492
std          7.998464
min          0.080000
25%          2.000000
50%          6.000000
75%         14.500000
max         41.250000
Name: hoeveelheid_uur, dtype: float64

In [120]:
df.head()

,EmployeeId,ServiceLineId_x,PlanningGroupId,EquipmentGroupId,ClientId,TenantId_x,orderserviceline_id,servicelinesname,equipmentname,EquipmentType_y,...,med_totaal_opdrachten,hoeveelheid_baal,hoeveelheid_dag,hoeveelheid_hectare,hoeveelheid_kubieke_meter,hoeveelheid_meter,hoeveelheid_stuk,hoeveelheid_ton,heeft_extra_eenheid,hoeveelheid_uur
3,f91bcfbd-f8c7-4f8a-95fe-2d273f4f93cb,710359a1-420c-4c0a-8d88-567bb3d364d3,11.0,16.0,cc8746f1-233d-4a0a-9ab2-5740ee5d4209,39bf3eb6-b8c2-4832-8f92-d89e9e58ac38,1cb43320-483c-4801-9ee5-01bc341ee9fe,Grasland bemesten,Case IH Optum 300 CVX,1.0,...,2,0.0,0.0,0.00,0.0,0.0,0.0,0.0,False,16.0
9,e1046257-13e1-4768-8ab0-91311693cb12,5326814c-8451-41ca-950f-0e9fc9987afe,5.0,6.0,4e317786-55eb-448d-b439-f9d4f2944e09,a46b0d64-2b99-41a4-8137-0e589a9c246f,2a0517d6-ea8a-4030-8b1e-5ca7509a9490,Hakselaar + graspickup,CLAAS JAGUAR 940,1.0,...,0,0.0,0.0,1.46,0.0,0.0,0.0,0.0,True,1.0
11,e1046257-13e1-4768-8ab0-91311693cb12,e09290ef-e88a-4394-a37c-4857cfa39997,21.0,NaN,a914817e-a713-499a-b3be-d915390b5a6b,a46b0d64-2b99-41a4-8137-0e589a9c246f,cdc9513c-c105-4bca-8682-d8f2b31c9bbd,Spuiten grasland,NaN,NaN,...,3,0.0,0.0,5.00,0.0,0.0,0.0,0.0,True,1.0
12,e1046257-13e1-4768-8ab0-91311693cb12,e09290ef-e88a-4394-a37c-4857cfa39997,21.0,NaN,a914817e-a713-499a-b3be-d915390b5a6b,a46b0d64-2b99-41a4-8137-0e589a9c246f,c8c7ae45-3677-4317-8684-e885afe9b1a8,Spuiten grasland,NaN,NaN,...,5,0.0,0.0,6.00,0.0,0.0,0.0,0.0,True,1.0
13,2ab5274c-f094-4c72-a7e7-f14e8f0809cf,a90d3a4b-683b-4841-b97d-0a2a766b5a78,24.0,36.0,2a8f2410-4295-4e80-9077-67a2e10d723c,5e8016f5-e1fc-4e15-85c2-a1c8516aee7b,146c3d24-7b15-459a-9069-2e5791e84183,Zodebemesten enkelasser,VEENHUIS HDG 14000,2.0,...,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,False,2.0

In [121]:
df.columns.to_series().to_csv("columns_for_model_rister.csv", index=False)

In [122]:
df1 = df[df["heeft_extra_eenheid"] == True]

In [123]:
print(len(df1) / len(df) * 100)

6.7675957489472625

In [124]:
df1.to_csv("rister.csv")